// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AlertDbContext))]
    [Migration("20260110212019_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Entities.AlertCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisibleToNormalUsers")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("AlertCategory");
                });

            modelBuilder.Entity("Infrastructure.Entities.AlertInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AlertEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AlertStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlertCategoryId");

                    b.ToTable("AlertInfo");
                });

            modelBuilder.Entity("Infrastructure.Entities.MaintenanceInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlertId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlertId")
                        .IsUnique()
                        .HasFilter("[AlertId] IS NOT NULL");

                    b.ToTable("MaintenanceInfo");
                });

            modelBuilder.Entity("Infrastructure.Entities.ReleaseInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlertId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlertId")
                        .IsUnique()
                        .HasFilter("[AlertId] IS NOT NULL");

                    b.ToTable("ReleaseInfo");
                });

            modelBuilder.Entity("Infrastructure.Entities.UserAlertHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSeenDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsersEmail")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AlertId");

                    b.HasIndex("UsersEmail");

                    b.ToTable("UserAlertHistory");
                });

            modelBuilder.Entity("Infrastructure.Entities.Users", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdminUser")
                        .HasColumnType("bit");

                    b.HasKey("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Infrastructure.Entities.AlertInfo", b =>
                {
                    b.HasOne("Infrastructure.Entities.AlertCategory", "AlertCategory")
                        .WithMany("Alerts")
                        .HasForeignKey("AlertCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertCategory");
                });

            modelBuilder.Entity("Infrastructure.Entities.MaintenanceInfo", b =>
                {
                    b.HasOne("Infrastructure.Entities.AlertInfo", "AlertInfo")
                        .WithOne("MaintenanceInfo")
                        .HasForeignKey("Infrastructure.Entities.MaintenanceInfo", "AlertId");

                    b.Navigation("AlertInfo");
                });

            modelBuilder.Entity("Infrastructure.Entities.ReleaseInfo", b =>
                {
                    b.HasOne("Infrastructure.Entities.AlertInfo", "AlertInfo")
                        .WithOne("ReleaseInfo")
                        .HasForeignKey("Infrastructure.Entities.ReleaseInfo", "AlertId");

                    b.Navigation("AlertInfo");
                });

            modelBuilder.Entity("Infrastructure.Entities.UserAlertHistory", b =>
                {
                    b.HasOne("Infrastructure.Entities.AlertInfo", "AlertInfo")
                        .WithMany("AlertHistory")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Entities.Users", null)
                        .WithMany("UserAlerts")
                        .HasForeignKey("UsersEmail");

                    b.Navigation("AlertInfo");
                });

            modelBuilder.Entity("Infrastructure.Entities.AlertCategory", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("Infrastructure.Entities.AlertInfo", b =>
                {
                    b.Navigation("AlertHistory");

                    b.Navigation("MaintenanceInfo");

                    b.Navigation("ReleaseInfo");
                });

            modelBuilder.Entity("Infrastructure.Entities.Users", b =>
                {
                    b.Navigation("UserAlerts");
                });
#pragma warning restore 612, 618
        }
    }
}
